=== dungcao/marsa/Marketplace/web/schemas/market.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	version="0.1"
	targetNamespace="http://realmarket.com/schemas/market"
	xmlns:market="http://realmarket.com/schemas/market"
	elementFormDefault="qualified">
	<xs:annotation>
		<xs:documentation>
			Realtime Data Marketplace
			Copyright 2014, Tien-Dung Cao, Tran-Vu Pham, Quang-Hieu Vu, Hong-Linh Truong

			Licensed under the Apache License, Version 2.0 (the "License");
			you may not use this file except in compliance with the License.
			You may obtain a copy of the License at
			http://www.apache.org/licenses/LICENSE-2.0

			Unless required by applicable law or agreed to in writing, software
			distributed under the License is distributed on an "AS IS" BASIS,
			WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
			See the License for the specific language governing permissions and
			limitations under the License.
		</xs:documentation>
	</xs:annotation>
    
	<xs:element name="marketcatalog" type="market:MarketCatalog"/>
	<xs:complexType name="MarketCatalog">
		<xs:sequence>
			<xs:element name="service" type="market:MarketService" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="MarketService">
		<xs:sequence>
                        <xs:element name="serviceuuid" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="servicename" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="provider" type="xs:string" minOccurs="1" maxOccurs="1"/>
                        <xs:element name="servicedescription" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="servicecost" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="servicecontractmodels" type="market:MarketContract" minOccurs="1" maxOccurs="1"/>
			<xs:element name="servicecategories" type="market:Category" minOccurs="1" maxOccurs="1"/>
			<xs:element name="qos" type="market:EntryContent" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="servicedatabus" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="datastream" type="market:MarketDataStream" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="MarketDataStream">
		<xs:sequence>
			<xs:element name="streamuuid" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="device" type="market:EntryContent" minOccurs="0" maxOccurs="1"/>
			<xs:element name="datadescription" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="datacost" type="xs:string" minOccurs="0" maxOccurs="1"/> 
			<xs:element name="datacontract" type="market:EntryContent" minOccurs="0" maxOccurs="1"/>   
			<xs:element name="datatype" type="market:EntryContent" minOccurs="1" maxOccurs="1"/>   
			<xs:element name="datacategory" type="market:EntryContent" minOccurs="0" maxOccurs="1"/>
			<xs:element name="streamdatabus" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="timeseries" type="xs:integer" minOccurs="1" maxOccurs="1"/>
                        <xs:element name="uncertainly" type="xs:integer" minOccurs="0" maxOccurs="1"/>
			<xs:element name="dataorigin" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="datarate" type="xs:integer" minOccurs="1" maxOccurs="1"/>
			<xs:element name="latency" type="xs:integer" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
        
        <!-- contract model -->
        <xs:complexType name="MarketContract">
		<xs:sequence>
			<xs:element name="contractmodel" type="market:EntryContent" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<!-- this is used to describe data represented by an external model: rdf, xml, etc. -->
	<xs:complexType name="EntryContent">
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="src" type="xs:anyURI"/>
	</xs:complexType>

	<!-- category -->
	<xs:complexType name="Category">
            <xs:sequence>
		<xs:element name="category" type="market:EntryContent" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
	</xs:complexType>
</xs:schema>

=== dungcao/marsa/Marketplace/build/web/schemas/servicetesting.xml
<?xml version="1.0" encoding="UTF-8"?>
<market:marketcatalog xmlns:market="http://realtime.datamarketplace.com/schemas/market" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="./market.xsd">
	<market:service>
		<market:servicename>Service testing</market:servicename>
		<market:provider>Marketplace developer</market:provider>
		<market:servicedescription>This service provider a list of stream use to test the market platform.</market:servicedescription>
		<market:servicecost type="application/xml">
			<marketpm:SizePrice xmlns:marketpm="http://realtime.datamarketplace.com/schemas/pricing" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="./pricingmodel.xsd">
				<marketpm:description>Pricing model based on data size</marketpm:description>
				<marketpm:price>100</marketpm:price>
                                <marketpm:dataSize>100</marketpm:dataSize>
				<marketpm:dataUnit>Mb</marketpm:dataUnit>
			</marketpm:SizePrice>
			<marketpm:APIPrice xmlns:marketpm="http://realtime.datamarketplace.com/schemas/pricing" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="./pricingmodel.xsd">
				<marketpm:description>Pricing model based on API handle</marketpm:description>
				<marketpm:price>10</marketpm:price>
				<marketpm:numberObject>10000</marketpm:numberObject>
			</marketpm:APIPrice>
			<marketpm:PlanPrice xmlns:marketpm="http://realtime.datamarketplace.com/schemas/pricing" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="./pricingmodel.xsd">
				<marketpm:description>Pricing model based on time plan</marketpm:description>
				<marketpm:price>20</marketpm:price>
				<marketpm:timeDuration>1</marketpm:timeDuration>
				<marketpm:timeUnit>Day</marketpm:timeUnit>
			</marketpm:PlanPrice>
			<marketpm:SubscriptionPrice xmlns:marketpm="http://realtime.datamarketplace.com/schemas/pricing" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="./pricingmodel.xsd">
				<marketpm:description>Pricing model based on subscription</marketpm:description>
				<marketpm:price>10</marketpm:price>
				<marketpm:timeDuration>1</marketpm:timeDuration>
                                <marketpm:timeUnit>Hour</marketpm:timeUnit>
				<marketpm:timeGroup>
					<marketpm:priceExtra>50</marketpm:priceExtra>
					<marketpm:from>2014-04-10T12:00:00</marketpm:from>
					<marketpm:to>2014-04-31T12:00:00</marketpm:to>
					<marketpm:repeat>yes</marketpm:repeat>
				</marketpm:timeGroup>
			</marketpm:SubscriptionPrice>
                        <!-- current version do not support this plan-->
			<marketpm:UnitPrice xmlns:marketpm="http://realtime.datamarketplace.com/schemas/pricing" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://realtime.datamarketplace.com/schemas/pricing pricingmodel.xsd">
				<marketpm:description>Pricing model based on data unit</marketpm:description>
				<marketpm:price>498.88</marketpm:price>
				<marketpm:streamGroup>
                                        <marketpm:stream>
                                            <marketpm:streamRef>ref#1</marketpm:streamRef>
                                            <!-- you can choose either data size or time duration -->
                                            <marketpm:dataSize>10</marketpm:dataSize>
                                            <marketpm:dataUnit>Gb</marketpm:dataUnit>
                                            <marketpm:from>2013-10-10T12:00:00</marketpm:from>
                                            <marketpm:to>2013-10-31T12:00:00</marketpm:to>
                                            <marketpm:repeat>no</marketpm:repeat>
                                        </marketpm:stream>
				</marketpm:streamGroup>
			</marketpm:UnitPrice>
		</market:servicecost>
		<market:servicecontract type="application/xml">
			<marketcm:UserCentricContract xmlns:marketcm="http://realtime.datamarketplace.com/schemas/contract" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="./contractmodel.xsd">
				<marketcm:description>Contract model focusing on contraints at provider side</marketcm:description>
				<marketcm:completeness>1.0</marketcm:completeness>
				<marketcm:reliability>1.0</marketcm:reliability>
				<marketcm:accuracy>1.0</marketcm:accuracy>
				<marketcm:consistency>1.0</marketcm:consistency>
				<marketcm:interpretability>1.0</marketcm:interpretability>
				<marketcm:indemnification>yes</marketcm:indemnification>
				<marketcm:limitation>no</marketcm:limitation>
			</marketcm:UserCentricContract>
		</market:servicecontract>
		<market:servicecategory label="" scheme="http://tempuri.org/daas" term="DaaS"/>
		<market:qos type="N/A" src="http://tempuri.org/qos"/>
		<market:servicedatabus>tcp://128.130.172.215:1883</market:servicedatabus>
		
		<market:datastream>
			<!--market:streamRef>ref#1</market:streamRef-->
			<market:device type="simulated sensor" src="http://tempuri.org/simulatedsensor"/>
			<market:datadescription>Simulated sensor 1</market:datadescription>
			<market:datatype type="text/csv" src="http://tempuri.org/text/csv"/>
			<market:pubsubdatabus>tcp://128.130.172.215:1883</market:pubsubdatabus>
			<market:timeseries>5</market:timeseries>
			<market:dataorigin>HCM, VN</market:dataorigin>
			<market:datarate>360</market:datarate>
			<market:latency>10</market:latency>
                </market:datastream>
    <market:datastream>
			<!--market:streamRef>ref#1</market:streamRef-->
			<market:device type="simulated sensor" src="http://tempuri.org/simulatedsensor"/>
			<market:datadescription>Simulated sensor 2</market:datadescription>
			<market:datatype type="text/csv" src="http://tempuri.org/text/csv"/>
			<market:pubsubdatabus>tcp://128.130.172.215:1883</market:pubsubdatabus>
			<market:timeseries>5</market:timeseries>
			<market:dataorigin>HCM, VN</market:dataorigin>
			<market:datarate>360</market:datarate>
			<market:latency>10</market:latency>
                </market:datastream>
		<market:datastream>
			<!--market:streamRef>ref#1</market:streamRef-->
			<market:device type="simulated sensor" src="http://tempuri.org/simulatedsensor"/>
			<market:datadescription>Simulated sensor 3</market:datadescription>
			<market:datatype type="text/csv" src="http://tempuri.org/text/csv"/>
			<market:pubsubdatabus>tcp://128.130.172.215:1883</market:pubsubdatabus>
			<market:timeseries>5</market:timeseries>
			<market:dataorigin>HCM, VN</market:dataorigin>
			<market:datarate>360</market:datarate>
			<market:latency>10</market:latency>
                </market:datastream>
                <market:datastream>
			<!--market:streamRef>ref#1</market:streamRef-->
			<market:device type="simulated sensor" src="http://tempuri.org/simulatedsensor"/>
			<market:datadescription>Simulated sensor 4</market:datadescription>
			<market:datatype type="text/csv" src="http://tempuri.org/text/csv"/>
			<market:pubsubdatabus>tcp://128.130.172.215:1883</market:pubsubdatabus>
			<market:timeseries>5</market:timeseries>
			<market:dataorigin>HCM, VN</market:dataorigin>
			<market:datarate>360</market:datarate>
			<market:latency>10</market:latency>
                </market:datastream>
                <market:datastream>
			<!--market:streamRef>ref#1</market:streamRef-->
			<market:device type="simulated sensor" src="http://tempuri.org/simulatedsensor"/>
			<market:datadescription>Simulated sensor 5</market:datadescription>
			<market:datatype type="text/csv" src="http://tempuri.org/text/csv"/>
			<market:pubsubdatabus>tcp://128.130.172.215:1883</market:pubsubdatabus>
			<market:timeseries>5</market:timeseries>
			<market:dataorigin>HCM, VN</market:dataorigin>
			<market:datarate>360</market:datarate>
			<market:latency>10</market:latency>
                </market:datastream>
                <market:datastream>
			<!--market:streamRef>ref#1</market:streamRef-->
			<market:device type="simulated sensor" src="http://tempuri.org/simulatedsensor"/>
			<market:datadescription>Simulated sensor 6</market:datadescription>
			<market:datatype type="text/csv" src="http://tempuri.org/text/csv"/>
			<market:pubsubdatabus>tcp://128.130.172.215:1883</market:pubsubdatabus>
			<market:timeseries>5</market:timeseries>
			<market:dataorigin>HCM, VN</market:dataorigin>
			<market:datarate>360</market:datarate>
			<market:latency>10</market:latency>
                </market:datastream>
                <market:datastream>
			<!--market:streamRef>ref#1</market:streamRef-->
			<market:device type="simulated sensor" src="http://tempuri.org/simulatedsensor"/>
			<market:datadescription>Simulated sensor 7</market:datadescription>
			<market:datatype type="text/csv" src="http://tempuri.org/text/csv"/>
			<market:pubsubdatabus>tcp://128.130.172.215:1883</market:pubsubdatabus>
			<market:timeseries>5</market:timeseries>
			<market:dataorigin>HCM, VN</market:dataorigin>
			<market:datarate>360</market:datarate>
			<market:latency>10</market:latency>
                </market:datastream>
                <market:datastream>
			<!--market:streamRef>ref#1</market:streamRef-->
			<market:device type="simulated sensor" src="http://tempuri.org/simulatedsensor"/>
			<market:datadescription>Simulated sensor 8</market:datadescription>
			<market:datatype type="text/csv" src="http://tempuri.org/text/csv"/>
			<market:pubsubdatabus>tcp://128.130.172.215:1883</market:pubsubdatabus>
			<market:timeseries>5</market:timeseries>
			<market:dataorigin>HCM, VN</market:dataorigin>
			<market:datarate>360</market:datarate>
			<market:latency>10</market:latency>
                </market:datastream>
                <market:datastream>
			<!--market:streamRef>ref#1</market:streamRef-->
			<market:device type="simulated sensor" src="http://tempuri.org/simulatedsensor"/>
